@base=https://localhost:7294/PdfContainer
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImM0ZjE5NmFjLTAxNDItNGY2OC05OWIwLWIxN2MwMzAxMzg1NCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IlNhamFsIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkdoaW1pcmUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzYWphbEBleGFtcGxlLmNvbSIsImV4cCI6MTcwMTI2NzM1NywiaXNzIjoiV29ydGhSZWFkcyIsImF1ZCI6IldvcnRoUmVhZHNBdWRpZW5jZSJ9.eUFFrKJJP3aXdh7UEzbcHh5aXxDPWMfgZSj5d64roAo
@ContainerId="d186e278-a8c9-4c8e-b82f-80682c542e65"

POST {{base}}/Create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "Name": "Tech"
}

########### Add pdf to container

POST {{base}}/AddPdf
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "ContainerId": {{ContainerId}},
    "Url": "https://bigthink.com/the-learning-curve/attention/"
}


######################## Get Owned Containers

GET {{base}}/OwnedContainers
Authorization: Bearer {{token}}

