@code=b229faf0-613a-2bab-e921-5da1bc
@key=109702-237c18b85b8e68991a14319
#sajaluj : f8d2e92b-3a9b-57c7-c9bb-3ea186
#sajaluj access token: 5279f888-e443-4bd9-fa73-b9382f
#nospamsajal at: 155c3f99-2b90-423e-1bd1-0aaf1d


POST https://getpocket.com/v3/oauth/request
Content-Type: application/json

{
    "consumer_key":"109702-237c18b85b8e68991a14319",
    "redirect_uri":"WorthReads:authorizationFinished"
}

####### Request token to access token.

POST https://getpocket.com/v3/oauth/authorize
Content-Type: application/json

{
    "consumer_key": "109702-237c18b85b8e68991a14319",
    "code": "2dba2dd1-4558-f5c9-1467-2ac36e"
}

########## Get user's saves

POST https://getpocket.com/v3/get
Content-Type: application/json

{
    "consumer_key": "109702-237c18b85b8e68991a14319",
    "access_token": "155c3f99-2b90-423e-1bd1-0aaf1d"
}

######## Register the request token.
#AuthorizeURL = https://getpocket.com/auth/authorize?request_token=df8e8c0e-20a8-65f2-d5c5-4eb1c6&redirect_uri=localhost