@base=https://localhost:7294/Reads
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6Ijc4OTk2MTg4LTIzY2YtNGJhNC04MzM3LTUyN2ZkMzM2MjhkZCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2dpdmVubmFtZSI6IlNhamFsIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkdoaW1pcmUiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzYWphbEBleGFtcGxlLmNvbSIsImV4cCI6MTcwMDY2MDE5NCwiaXNzIjoiV29ydGhSZWFkcyIsImF1ZCI6IldvcnRoUmVhZHNBdWRpZW5jZSJ9.TaBpqqkZ4h8kDRqOahDp3IhwcL_imCHuTIddLwI-KUE

GET {{base}}