@base=https://localhost:5000/Users

POST {{base}}/Register
Content-Type: application/json

{
    "FirstName": "Sajal",
    "LastName": "Ghimire",
    "Email": "sajal1@example.com",
    "Password": "Abc123!@#"
}

############ Login ############

POST {{base}}/Login
Content-Type: application/json

{
    "Email": "sajal1@example.com",
    "Password": "Abc123!@#"
}

###############
GET {{base}}/Test

